services:
  # 1. Backend Szolgáltatás
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./server/config/.env
    volumes:
      - ./server:/app             # Élőben összeköti a te server/ mappádat a konténer /app mappájával!
      - /app/node_modules         # Megvédi a konténeren belüli node_modules-t

  # 2. Frontend Szolgáltatás
  frontend:
    build: ./client
    ports:
      - "5175:5175"
    volumes:
      - ./client:/app             # Élőben összeköti a te client/ mappádat a konténer /app mappájával!
      - /app/node_modules         # Megvédi a konténeren belüli node_modules-t
